added Elio's portfolio
emmabostian/developer-portfolios pull request #316
Opened 2020-10-10 20:43 UTC by lopeselio

You can check my portfolio at https://develioper.vercel.app/  Request to join the family

2020-10-11 04:48 UTC, avipatilpro approved these changes

2020-10-16 15:41 UTC, jakeherp requested changes
Please add in alphabetical order.

2020-10-17 05:34 UTC, avipatilpro requested changes
.

2020-10-18 04:02 UTC, lopeselio commented
Hey @jakeherp Thanks for informing me. Will definitely do!

2020-10-18 09:51 UTC, closed without merging